language: node_js
node_js: 8
sudo: required
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - npm run test
cache:
  directories:
    - node_modules
